import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { Stack, useRouter } from 'expo-router';
import { useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { BottomNav, Button, Field, Icon, Overlay, RoundButton, SelectField, StatusBadge, Tag, Toast, type AmberIcon } from '@/components/ui/amber-kit';
import { AppColors as C, FontFamily as F, TypeScale, WarmShadow } from '@/constants/theme';

const sections = [
  { id: 'colors', name: 'Color palette', icon: 'sun', group: 'FOUNDATIONS' },
  { id: 'type', name: 'Typography', icon: 'type', group: 'FOUNDATIONS' },
  { id: 'spacing', name: 'Spacing & shape', icon: 'grid', group: 'FOUNDATIONS' },
  { id: 'buttons', name: 'Buttons & actions', icon: 'mouse-pointer', group: 'COMPONENTS' },
  { id: 'inputs', name: 'Inputs & controls', icon: 'sliders', group: 'COMPONENTS' },
  { id: 'chips', name: 'Chips & badges', icon: 'tag', group: 'COMPONENTS' },
  { id: 'cards', name: 'Social cards', icon: 'layers', group: 'COMPONENTS' },
  { id: 'navigation', name: 'Navigation', icon: 'compass', group: 'COMPONENTS' },
  { id: 'overlays', name: 'Overlays & feedback', icon: 'message-square', group: 'COMPONENTS' },
  { id: 'icons', name: 'Iconography', icon: 'smile', group: 'COMPONENTS' },
] as const;
const palette = [
  { name: 'Golden hour', role: 'Primary', hex: C.primary }, { name: 'Warm orange', role: 'Accent', hex: C.accent },
  { name: 'Cream white', role: 'Background', hex: C.background }, { name: 'Pure white', role: 'Surface', hex: C.surface },
  { name: 'Soft beige', role: 'Section', hex: C.section }, { name: 'Warm sand', role: 'Border', hex: C.border },
  { name: 'Espresso', role: 'Primary text', hex: C.text }, { name: 'Cocoa', role: 'Secondary text', hex: C.textSecondary },
];
const icons: AmberIcon[] = ['home', 'users', 'plus-circle', 'message-circle', 'user', 'search', 'map-pin', 'calendar', 'clock', 'sun', 'music', 'coffee', 'smile', 'shield', 'check-circle', 'star', 'bookmark', 'bell', 'send', 'sliders', 'camera', 'navigation', 'flag', 'more-horizontal'];

function Label({ children }: { children: React.ReactNode }) { return <Text style={s.eyebrow}>{children}</Text>; }
function Copy({ children }: { children: React.ReactNode }) { return <Text style={s.copy}>{children}</Text>; }
function Panel({ title, number, subtitle, children, onLayout }: { title: string; number: string; subtitle: string; children: React.ReactNode; onLayout?: (y: number) => void }) {
  return <View onLayout={e => onLayout?.(e.nativeEvent.layout.y)} style={s.panel}><View style={s.panelHeading}><View style={s.row}><Text style={s.sectionNumber}>{number}</Text><Text accessibilityRole="header" style={s.panelTitle}>{title}</Text></View><Icon name="arrow-up-right" size={16} color={C.textSecondary} /></View><Text style={s.panelSubtitle}>{subtitle}</Text>{children}</View>;
}

export default function DesignSystem() {
  const router = useRouter();
  const { width } = useWindowDimensions();
  const desktop = width >= 1100;
  const columns = width >= 780;
  const scroll = useRef<ScrollView>(null);
  const [positions, setPositions] = useState<Record<string, number>>({});
  const [category, setCategory] = useState('Overview');
  const [activeSection, setActiveSection] = useState('colors');
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(['Tonight', 'Chill']);
  const [groupSize, setGroupSize] = useState('2–4 people');
  const [isPublic, setPublic] = useState(true);
  const [nav, setNav] = useState('Home');
  const [overlay, setOverlay] = useState<'join' | 'sheet' | 'tokens' | null>(null);
  const [toast, setToast] = useState('');
  const [saved, setSaved] = useState(false);
  const [joined, setJoined] = useState(false);
  const [following, setFollowing] = useState(false);
  const [message, setMessage] = useState('');
  const [messages, setMessages] = useState<string[]>([]);
  const show = (id: string) => {
    const section = sections.find(item => item.id === id)!;
    return (category === 'Overview' || section.group === category.toUpperCase()) && (!query || `${section.name} ${section.id}`.toLowerCase().includes(query.toLowerCase()));
  };
  const jump = (id: string) => {
    setActiveSection(id); setCategory('Overview'); setQuery('');
    requestAnimationFrame(() => scroll.current?.scrollTo({ y: Math.max(0, (positions[id] ?? 0) - 24), animated: true }));
  };
  const toggleTag = (value: string) => setSelected(items => items.includes(value) ? items.filter(item => item !== value) : [...items, value]);
  const note = (value: string) => setToast(value);
  const mark = (id: string) => (y: number) => setPositions(current => current[id] === y ? current : { ...current, [id]: y });
  const markGroup = (ids: string[], y: number) => setPositions(current => {
    if (ids.every(id => current[id] === y)) return current;
    return ids.reduce((next, id) => ({ ...next, [id]: y }), current);
  });
  const visibleSections = sections.filter(item => show(item.id));

  return <SafeAreaView edges={['top', 'bottom']} style={s.safe}>
    <Stack.Screen options={{ headerShown: false, title: 'Amber — ChillWithHomies design system' }} />
    <View style={s.app}>
      {desktop && <View style={s.sidebar}>
        <View style={[s.row, { gap: 10, paddingHorizontal: 12 }]}><View style={s.brandIcon}><Icon name="sun" size={24} /></View><View><Text style={s.brand}>amber<Text style={{ color: C.accent }}>.</Text></Text><Text style={s.brandCaption}>by ChillWithHomies</Text></View></View>
        <Pressable accessibilityRole="button" onPress={() => { setCategory('Overview'); setQuery(''); scroll.current?.scrollTo({ y: 0, animated: true }); }} style={s.overviewLink}><Icon name="grid" size={17} /><Text style={s.navLabel}>System overview</Text><Text style={s.versionMini}>1.0</Text></Pressable>
        {['FOUNDATIONS', 'COMPONENTS'].map(group => <View key={group} style={{ marginTop: 24 }}><Text style={s.sidebarGroup}>{group}</Text>{sections.filter(item => item.group === group).map(item => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Go to ${item.name}`} onPress={() => jump(item.id)} style={({ pressed }) => [s.sidebarLink, activeSection === item.id && s.sidebarLinkActive, pressed && { opacity: 0.6 }]}><Icon name={item.icon} size={17} color={activeSection === item.id ? C.accentText : C.textSecondary} /><Text style={[s.sidebarText, activeSection === item.id && { color: C.text, fontFamily: F.bodySemiBold }]}>{item.name}</Text></Pressable>)}</View>)}
        <View style={{ flex: 1 }} />
        <View style={s.sidebarNote}><View style={s.row}><Icon name="heart" size={17} color={C.accentText} /><Text style={s.smallHeading}>Made for good company.</Text></View><Text style={s.caption}>A little warmth. A lot of connection.</Text></View>
        <View style={[s.row, { padding: 12 }]}><View style={s.greenDot} /><Text style={s.caption}>Version 1.0 · September 2026</Text></View>
      </View>}

      <View style={{ flex: 1, minWidth: 0 }}>
        <View style={[s.topbar, { paddingHorizontal: desktop ? 40 : 20 }]}><View style={s.row}>{!desktop && <View style={s.smallBrand}><Icon name="sun" size={20} /></View>}<Text style={s.breadcrumb}>{desktop ? 'Design system' : 'amber.'}</Text><Icon name="chevron-right" size={14} color={C.textSecondary} /><Text style={s.navLabel}>Overview</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open meetup app" onPress={() => router.push('/(tabs)')} style={s.previewLink}><Text style={s.previewText}>{width > 450 ? 'Open meetup app' : 'App'}</Text><Icon name="arrow-up-right" size={16} /></Pressable></View>
        <ScrollView ref={scroll} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={[s.content, { paddingHorizontal: desktop ? 40 : 20 }]}>
          <View style={[s.pageHeading, !columns && { alignItems: 'flex-start' }]}><View style={{ flex: 1 }}><View style={s.row}><Label>THE AMBER DESIGN SYSTEM</Label><StatusBadge label="v1.0" tone="neutral" /></View><Text accessibilityRole="header" style={[s.title, !columns && { fontSize: 32, lineHeight: 40 }]}>Good times start here.</Text><Text style={s.subtitle}>Thoughtful little pieces. Meaningful real-world connections.</Text></View>{columns && <Button label="Design tokens" icon="code" variant="ghost" onPress={() => setOverlay('tokens')} />}</View>

          <LinearGradient colors={['#FFF1C3', '#FFDB8A', '#F8BD6B']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0.8 }} style={[s.hero, !columns && { padding: 24 }]}>
            <View style={{ flex: 1, zIndex: 2 }}><View style={s.heroPill}><View style={s.amberDot} /><Text style={s.heroPillText}>A little more human.</Text></View><Text style={[s.heroTitle, !columns && { fontSize: 27, lineHeight: 35 }]}>Less scrolling.{ '\n' }More showing up.</Text><Text style={s.heroCopy}>A warm, easy-going design language for{columns ? '\n' : ' '}finding your people and making a plan.</Text><View style={[s.row, { marginTop: 20, flexWrap: 'wrap' }]}>{['Warm by nature', 'Social at heart', 'Mobile first'].map(text => <View key={text} style={s.heroTag}><Icon name="check" size={12} /><Text style={s.heroTagText}>{text}</Text></View>)}</View></View>
            {columns && <View style={s.heroArt} accessible={false}><View style={s.orbit} /><View style={s.orbitInner} /><View style={s.sunDisc}><Icon name="smile" size={77} color="#8D531E" /></View><View style={s.floatingChat}><Icon name="message-circle" size={27} color={C.accentText} /><Text style={s.smallHeading}>See you tonight!</Text><Text>✌️</Text></View><View style={s.floatingPeople}><View style={[s.miniAvatar, { backgroundColor: '#FFF2BF' }]}><Text>J</Text></View><View style={[s.miniAvatar, { backgroundColor: '#EFBD93', marginLeft: -8 }]}><Text>M</Text></View><View style={[s.miniAvatar, { backgroundColor: '#D7E1BF', marginLeft: -8 }]}><Text>A</Text></View><Text style={s.heroTagText}>Your kind of people</Text></View><View style={s.sparkOne}><Icon name="sun" color={C.accentText} size={28} /></View><View style={s.sparkTwo}><Icon name="star" color={C.accentText} size={19} /></View></View>}
          </LinearGradient>

          <View style={[s.toolbar, !columns && { flexDirection: 'column', alignItems: 'stretch', gap: 16 }]}><View accessibilityRole="tablist" style={s.tabs}>{['Overview', 'Foundations', 'Components'].map(item => <Pressable key={item} accessibilityRole="tab" accessibilityLabel={item} accessibilityState={{ selected: category === item }} onPress={() => setCategory(item)} style={[s.tab, category === item && s.tabActive]}><Text style={[s.tabText, category === item && { color: C.text }]}>{item}</Text>{item === 'Components' && <Text style={s.tabCount}>7</Text>}</Pressable>)}</View><View style={{ width: columns ? 230 : '100%' }}><Field icon="search" placeholder="Find a component…" value={query} onChangeText={setQuery} /></View></View>

          {show('colors') && <Panel title="Color palette" number="01" subtitle="Sunshine, a splash of orange, and a soft place to land." onLayout={mark('colors')}>
            <View style={[s.swatches, !columns && { flexWrap: 'wrap' }]}>{palette.map((color, i) => <View key={color.name} style={[s.swatch, { width: columns ? '11.4%' : '22%' }]}><View style={[s.colorBlock, { backgroundColor: color.hex, borderColor: i === 2 || i === 3 ? C.border : color.hex }]}><Text style={[s.swatchIndex, { color: i > 5 ? '#FFFFFFCC' : '#2F241C88' }]}>0{i + 1}</Text></View><Text style={s.colorName}>{color.name}</Text><Text style={s.caption}>{color.role}</Text><Text selectable style={s.hex}>{color.hex}</Text></View>)}</View>
            <View style={[s.statusRow, !columns && { flexWrap: 'wrap' }]}><Text style={s.label}>A little clarity</Text><StatusBadge label="Success · #2E8B64" tone="green" icon="check-circle" /><StatusBadge label="Warning · #855C00" icon="alert-triangle" /><StatusBadge label="Error · #B53D31" tone="red" icon="alert-circle" /><StatusBadge label="Info · #45689B" tone="blue" icon="info" /></View>
          </Panel>}

          {show('type') && <Panel title="Typography" number="02" subtitle="A friendly voice, with just the right amount of personality." onLayout={mark('type')}>
            <View style={[s.typeGrid, !columns && { flexDirection: 'column' }]}><View style={s.typeIntro}><Text style={s.typeLetters}>Aa<Text style={{ color: C.accent }}>.</Text></Text><Text style={s.fontNames}>Manrope <Text style={{ color: C.textSecondary }}>+ Inter</Text></Text><Copy>Confident headings. Effortless reading.{ '\n' }Always human, never shouty.</Copy><View style={[s.row, { marginTop: 16 }]}><StatusBadge label="Manrope / 600, 700" tone="neutral" /><StatusBadge label="Inter / 400, 500, 600" tone="neutral" /></View></View><View style={s.typeRows}>{[
              ['Display', 'Make room for good times.', '32 / 39 · Bold', 'display'], ['Heading 1', 'Find your kind of people', '28 / 35 · Bold', 'h1'], ['Heading 2', 'Happening tonight', '22 / 29 · Bold', 'h2'], ['Heading 3', 'A little hello goes a long way', '18 / 24 · Semibold', 'h3'], ['Body', 'Good company is just around the corner.', '14 / 21 · Regular', 'body'], ['Label', 'Join this meetup', '13 / 18 · Semibold', 'label'], ['Caption', 'Tonight, 7:30 PM · 1.2 km away', '12 / 17 · Regular', 'caption'],
            ].map(([name, example, spec, token]) => <View key={name} style={s.typeRow}><Text style={s.typeLabel}>{name}</Text><View style={{ flex: 1 }}><Text style={[TypeScale[token as keyof typeof TypeScale], { color: C.text }, !columns && token === 'display' && { fontSize: 26 }]}>{example}</Text><Text style={s.typeSpec}>{spec}</Text></View></View>)}</View></View>
          </Panel>}

          {show('spacing') && <Panel title="Spacing & shape" number="03" subtitle="An 8pt rhythm keeps things calm. Rounded edges keep things friendly." onLayout={mark('spacing')}><View style={[s.shapeGrid, !columns && { flexDirection: 'column' }]}><View style={{ flex: 1 }}><Label>SPACE TO BREATHE</Label><View style={s.spaceExamples}>{[8, 16, 24, 32, 40].map(n => <View key={n} style={{ alignItems: 'center', gap: 8 }}><View style={{ width: n, height: 40, backgroundColor: C.primarySoft, borderLeftWidth: 2, borderRightWidth: 2, borderColor: C.primary }} /><Text style={s.caption}>{n}</Text></View>)}</View><Text style={s.caption}>4pt optical adjustment · 16pt gutters · 24pt sections</Text></View><View style={{ flex: 1 }}><Label>SOFT AROUND THE EDGES</Label><View style={s.spaceExamples}>{[['16', 16], ['24', 24], ['32', 32], ['Pill', 999]].map(([label, radius]) => <View key={label} style={{ alignItems: 'center', gap: 8 }}><View style={{ width: 48, height: 40, borderRadius: Number(radius), backgroundColor: C.section, borderWidth: 1, borderColor: C.border }} /><Text style={s.caption}>{label}</Text></View>)}</View><Text style={s.caption}>Warm shadow · 0 10 28 / espresso at 10%</Text></View></View></Panel>}

          <View onLayout={e => markGroup(['buttons', 'inputs', 'chips'], e.nativeEvent.layout.y)} style={[s.componentGrid, !columns && { flexDirection: 'column' }]}>
            {show('buttons') && <View style={s.column}><Panel title="Buttons & actions" number="04" subtitle="A clear invitation to join in."><View style={s.stack}><Label>PRIMARY & SECONDARY</Label><Button label="Join this meetup" icon="plus" onPress={() => setOverlay('join')} /><Button label="Explore meetups" variant="secondary" icon="compass" onPress={() => router.push('/(tabs)')} /><View style={s.twoButtons}><Button label="Maybe later" variant="ghost" small onPress={() => note('No rush. Find a meetup when you’re ready.')} style={{ flex: 1 }} /><Button label="Leave" variant="destructive" small onPress={() => { setJoined(false); note('Demo meetup left.'); }} style={{ flex: 1 }} /></View><Label>STATES & ICON BUTTONS</Label><View style={s.twoButtons}><Button label="Unavailable" disabled style={{ flex: 1 }} /><Button label="Joining" loading style={{ flex: 1 }} /></View><View style={s.row}><RoundButton icon="plus" label="Create a meetup" onPress={() => router.push('/(tabs)/create')} /><RoundButton icon="bookmark" label={saved ? 'Unsave meetup' : 'Save meetup'} selected={saved} onPress={() => { setSaved(!saved); note(saved ? 'Meetup removed from saved.' : 'Meetup saved for later.'); }} /><RoundButton icon="arrow-right" label="View meetup details" onPress={() => setOverlay('join')} /><RoundButton icon="more-horizontal" label="More meetup options" onPress={() => setOverlay('sheet')} /></View><Text style={s.caption}>48pt touch targets · 16pt radius · Press to try</Text></View></Panel></View>}
            {show('inputs') && <View style={s.column}><Panel title="Inputs & controls" number="05" subtitle="Easy to fill. Hard to get lost."><View style={s.stack}><Field label="Meetup title" placeholder="Give your plan a name" /><Field icon="search" accessibilityLabel="Example meetup search" placeholder="Search people, places, plans…" /><SelectField label="Group size" value={groupSize} options={['2–4 people', '5–8 people', '9–12 people']} onChange={setGroupSize} /><Field label="Location" icon="map-pin" placeholder="Add a meeting spot" error="Choose a place so everyone can find you." /><View style={s.between}><View><Text style={s.label}>Public meetup</Text><Text style={s.caption}>Let good company find you</Text></View><Switch accessibilityLabel="Public meetup" value={isPublic} onValueChange={setPublic} trackColor={{ false: C.border, true: C.primary }} thumbColor={C.surface} /></View></View></Panel></View>}
            {show('chips') && <View style={s.column}><Panel title="Chips & badges" number="06" subtitle="Find a vibe. Get the little details."><View style={s.stack}><Label>FILTER BY FEELING</Label><View style={s.wrap}>{(['Tonight', 'Nearby', 'Karaoke', 'Chill', 'Rooftop', '2–4 people'] as const).map((label, i) => <Tag key={label} label={label} icon={(['moon', 'map-pin', 'mic', 'coffee', 'sun', 'users'] as AmberIcon[])[i]} selected={selected.includes(label)} onPress={() => toggleTag(label)} />)}</View><Text style={s.caption}>{selected.length} selected · Tap to change the vibe</Text><View style={s.divider} /><Label>SMALL SIGNALS, BIG REASSURANCE</Label><View style={s.wrap}><StatusBadge label="Verified" tone="green" icon="shield" /><StatusBadge label="Open spots" tone="green" icon="users" /><StatusBadge label="Full" tone="neutral" icon="lock" /><StatusBadge label="Tonight" tone="amber" icon="moon" /><StatusBadge label="Almost full" tone="orange" icon="clock" /><StatusBadge label="New host" tone="blue" icon="smile" /></View><Text style={s.caption}>Status always pairs color with a clear label.</Text></View></Panel></View>}
          </View>

          {show('cards') && <Panel title="Social cards" number="07" subtitle="The plan, the people, and a reason to say yes." onLayout={mark('cards')}><View style={[s.cardGrid, !columns && { flexDirection: 'column' }]}>
            <View style={[s.eventCard, { flex: 1.15 }]}><View style={s.eventImageWrap}><Image source={require('@/assets/images/meetup-rooftop.png')} contentFit="cover" style={s.eventImage} accessibilityLabel="Friends gathering on a warm rooftop terrace" /><View style={s.imageBadges}><StatusBadge label="Tonight" icon="moon" /><RoundButton icon="bookmark" label={saved ? 'Unsave rooftop meetup' : 'Save rooftop meetup'} selected={saved} onPress={() => setSaved(!saved)} /></View></View><View style={s.eventBody}><View style={s.between}><StatusBadge label="Rooftop · Chill" tone="orange" /><Text style={s.caption}>1.2 km away</Text></View><Text style={s.eventTitle}>Golden hour, good company</Text><View style={s.row}><Icon name="clock" size={14} color={C.textSecondary} /><Text style={s.copy}>Tonight, 7:30 PM</Text></View><View style={s.row}><Icon name="map-pin" size={14} color={C.textSecondary} /><Text style={s.copy}>The Rooftop · District 1</Text></View><View style={s.eventFooter}><View style={s.row}><Image source={require('@/assets/images/profile-minh-anh.png')} style={s.hostAvatar} /><View><View style={s.row}><Text style={s.label}>Minh Anh</Text><Icon name="check-circle" size={13} color={C.success} /></View><Text style={s.caption}>{joined ? '5' : '4'} of 6 going</Text></View></View><Button label={joined ? 'Joined' : 'Join'} icon={joined ? 'check' : 'plus'} small onPress={() => setOverlay('join')} /></View></View></View>
            <View style={{ flex: 1, gap: 16 }}><View style={s.profileCard}><View style={s.between}><StatusBadge label="Your next good friend" tone="amber" /><Icon name="more-horizontal" color={C.textSecondary} /></View><View style={s.profileHead}><Image source={require('@/assets/images/profile-minh-anh.png')} style={s.profilePhoto} /><View style={{ flex: 1 }}><View style={s.row}><Text style={s.eventTitle}>Minh Anh</Text><Icon name="check-circle" size={17} color={C.success} /></View><Text style={s.copy}>Coffee, sunsets & good conversations.</Text></View></View><View style={s.profileStats}><View><Text style={s.statValue}>4.9 <Text style={{ color: C.accent }}>★</Text></Text><Text style={s.caption}>Host rating</Text></View><View style={s.statDivider} /><View><Text style={s.statValue}>18</Text><Text style={s.caption}>Meetups joined</Text></View><View style={s.statDivider} /><View><Text style={s.statValue}>7</Text><Text style={s.caption}>Plans hosted</Text></View></View><View style={s.wrap}><Tag label="Coffee" icon="coffee" /><Tag label="Rooftops" icon="sun" /><Tag label="Board games" icon="grid" /></View><Button label={following ? 'Following Minh Anh' : 'Say hello'} icon={following ? 'check' : 'user-plus'} variant="secondary" onPress={() => { setFollowing(!following); note(following ? 'You unfollowed Minh Anh in this demo.' : 'You’re following Minh Anh in this demo.'); }} /></View><View style={s.safetyCard}><View style={s.safetyIcon}><Icon name="shield" color={C.success} /></View><View style={{ flex: 1 }}><Text style={s.smallHeading}>Good company. Safer meetups.</Text><Text style={s.copy}>Meet in public, respect boundaries, and look out for each other.</Text></View></View></View>
          </View></Panel>}

          <View onLayout={e => markGroup(['navigation', 'overlays'], e.nativeEvent.layout.y)} style={[s.componentGrid, !columns && { flexDirection: 'column' }]}>
            {show('navigation') && <View style={s.column}><Panel title="Navigation" number="08" subtitle="Five familiar places. One easy way around."><View style={s.stack}><Label>TOP APP BAR</Label><View style={s.appBar}><RoundButton icon="arrow-left" label="Preview back action" onPress={() => note('Back takes you to the previous screen.')} /><Text style={s.smallHeading}>Tonight’s plans</Text><RoundButton icon="bell" label="Preview notifications" onPress={() => note('You’re all caught up. More good times soon.')} /></View><Label>BOTTOM NAVIGATION</Label><BottomNav active={nav} onChange={setNav} /><Text style={s.caption}>Active destination: {nav} · Tap any tab to preview</Text><View style={s.navNote}><Icon name="smartphone" color={C.accentText} /><Text style={[s.copy, { flex: 1 }]}>Keep labels visible. Respect the device’s bottom safe area.</Text></View></View></Panel></View>}
            {show('overlays') && <View style={s.column}><Panel title="Overlays & feedback" number="09" subtitle="A gentle nudge, never an interruption."><View style={s.stack}><View style={s.sheetPreview}><View style={s.handle} /><View style={s.row}><View style={s.sheetSmiley}><Icon name="smile" color={C.accentText} size={25} /></View><View style={{ flex: 1 }}><Text style={s.smallHeading}>Make room for a new memory.</Text><Text style={s.copy}>Your people are waiting. Shall we?</Text></View></View><Button label="Preview join modal" onPress={() => setOverlay('join')} /></View><View style={s.twoButtons}><Button label="Bottom sheet" variant="ghost" icon="chevrons-up" onPress={() => setOverlay('sheet')} style={{ flex: 1 }} /><Button label="Show toast" variant="ghost" icon="check-circle" onPress={() => note('You’re in! Let the good times begin.')} style={{ flex: 1 }} /></View></View></Panel></View>}
          </View>

          {show('icons') && <Panel title="Iconography" number="10" subtitle="Familiar shapes with a friendly, rounded touch. Feather icons · 24pt grid · 2pt stroke." onLayout={mark('icons')}><View style={s.iconGrid}>{icons.map(icon => <View key={icon} style={s.iconTile}><Icon name={icon} size={24} /><Text style={s.iconName}>{icon}</Text></View>)}</View><Text style={[s.caption, { marginTop: 16 }]}>Use 16pt inline, 20pt in controls, and 24pt in navigation. Always label icon-only actions.</Text></Panel>}

          {(category === 'Overview' && !query) && <Panel title="A conversation starter" number="+" subtitle="The same warm language, carried into group chat."><View style={[s.chatGrid, !columns && { flexDirection: 'column' }]}><View style={{ flex: 1, gap: 12 }}><View style={s.receivedBubble}><Text style={s.chatAuthor}>MINH ANH</Text><Copy>I’ll grab the table by the window. See you soon! ☀️</Copy><Text style={s.chatTime}>7:12 PM</Text></View><View style={s.sentBubble}><Copy>Perfect! On my way 🙌</Copy><Text style={s.chatTime}>7:14 PM · Read</Text></View>{messages.map((text, i) => <View key={i} style={s.sentBubble}><Copy>{text}</Copy><Text style={s.chatTime}>Just now · Demo</Text></View>)}</View><View style={{ flex: 1, gap: 16 }}><View style={s.wrap}><Tag label="Poll" icon="bar-chart-2" onPress={() => note('Demo poll: Coffee or rooftop?')} /><Tag label="Location" icon="map-pin" onPress={() => note('Meeting spot: The Rooftop, District 1.')} /><Tag label="ETA" icon="navigation" onPress={() => { setMessages(items => [...items, 'I’ll be there in 10 minutes!']); }} /></View><Field label="Message the group" placeholder="Break the ice…" value={message} onChangeText={setMessage} multiline /><Button label="Send demo message" icon="send" disabled={!message.trim()} onPress={() => { if (message.trim()) { setMessages(items => [...items, message.trim()]); setMessage(''); } }} /></View></View></Panel>}
          {visibleSections.length === 0 && <View style={s.empty}><Icon name="search" size={32} color={C.accentText} /><Text style={s.panelTitle}>No pieces found just yet.</Text><Copy>Try “buttons”, “cards”, or “color”.</Copy><Button label="Clear search" variant="secondary" onPress={() => { setQuery(''); setCategory('Overview'); }} /></View>}
          <View style={[s.footer, !columns && { flexDirection: 'column', gap: 12 }]}><View style={s.row}><Icon name="sun" size={18} color={C.accentText} /><Text style={s.footerText}>Built for the moments between “hello” and “let’s do this.”</Text></View><Text style={s.caption}>AMBER / CHILLWITHHOMIES</Text></View>
        </ScrollView>
      </View>
    </View>
    <Overlay visible={overlay === 'join'} title={joined ? 'You’re on the list!' : 'A good plan starts with yes.'} onClose={() => setOverlay(null)}><View style={s.sheetSmiley}><Icon name={joined ? 'check' : 'sun'} size={28} color={C.accentText} /></View><Text style={s.eventTitle}>Golden hour, good company</Text><Copy>Tonight, 7:30 PM · The Rooftop, District 1</Copy><StatusBadge label={`${joined ? 5 : 4} of 6 going · Verified host`} tone="green" icon="shield" /><Copy>{joined ? 'This preview keeps your spot for this session. Say hello when you arrive.' : 'Come as you are. Meet in a public place, respect everyone’s boundaries, and pay for your own order.'}</Copy><Button label={joined ? 'Sounds good' : 'Join this meetup'} icon={joined ? 'check' : 'plus'} onPress={() => { if (!joined) { setJoined(true); note('You joined the demo meetup. See you tonight!'); } setOverlay(null); }} /><Button label="Maybe later" variant="ghost" onPress={() => setOverlay(null)} /></Overlay>
    <Overlay visible={overlay === 'sheet'} title="Find your kind of evening" onClose={() => setOverlay(null)} sheet><Copy>A few good filters can lead to a great night.</Copy><View style={s.wrap}>{['Tonight', 'Nearby', 'Karaoke', 'Chill', 'Rooftop', '2–4 people'].map(label => <Tag key={label} label={label} selected={selected.includes(label)} onPress={() => toggleTag(label)} />)}</View><Button label={`Apply ${selected.length} filters`} icon="check" onPress={() => { setOverlay(null); note(`${selected.length} filters applied to the component preview.`); }} /><Button label="Reset filters" variant="ghost" onPress={() => setSelected([])} /></Overlay>
    <Overlay visible={overlay === 'tokens'} title="The building blocks" onClose={() => setOverlay(null)}><Copy>Shared React Native tokens power every component in this library. Select and copy the values below.</Copy><Text selectable style={s.tokenCode}>{JSON.stringify({ colors: C, spacing: [8, 16, 24, 32, 40], radius: [16, 24, 32, 999], touchTarget: 48, fonts: { heading: 'Manrope', body: 'Inter' } }, null, 2)}</Text></Overlay>
    <Toast message={toast} onClose={() => setToast('')} />
  </SafeAreaView>;
}

const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.background }, app: { flex: 1, flexDirection: 'row' }, row: { flexDirection: 'row', alignItems: 'center', gap: 8 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, stack: { gap: 16 },
  copy: { ...TypeScale.body, fontSize: 13, color: C.textSecondary }, caption: { ...TypeScale.caption, fontSize: 11, color: C.textSecondary }, label: { ...TypeScale.label, fontSize: 12, color: C.text }, smallHeading: { fontFamily: F.headingBold, fontSize: 13, color: C.text }, eyebrow: { fontFamily: F.bodySemiBold, fontSize: 10, letterSpacing: 1.6, color: C.textSecondary },
  sidebar: { width: 244, borderRightWidth: 1, borderColor: C.border, padding: 20, backgroundColor: '#FFFBF4' }, brandIcon: { width: 44, height: 44, borderRadius: 15, backgroundColor: C.primary, alignItems: 'center', justifyContent: 'center' }, brand: { fontFamily: F.headingBold, fontSize: 28, color: C.text, letterSpacing: -1.5 }, brandCaption: { fontFamily: F.body, fontSize: 9, color: C.textSecondary },
  overviewLink: { marginTop: 36, minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#F2D892', borderRadius: 12, backgroundColor: '#FFF0C7', paddingHorizontal: 12 }, navLabel: { fontFamily: F.bodySemiBold, fontSize: 12, color: C.text }, versionMini: { marginLeft: 'auto', fontFamily: F.bodyMedium, fontSize: 10, color: C.accentText }, sidebarGroup: { fontFamily: F.bodySemiBold, color: '#A09282', fontSize: 9, letterSpacing: 1.5, paddingHorizontal: 12, marginBottom: 8 }, sidebarLink: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 12, minHeight: 42, borderRadius: 10 }, sidebarLinkActive: { backgroundColor: '#FFF3DF' }, sidebarText: { fontFamily: F.body, fontSize: 12, color: C.textSecondary }, sidebarNote: { backgroundColor: '#FFF3DE', borderRadius: 16, padding: 12, gap: 8, marginTop: 24 }, greenDot: { width: 6, height: 6, backgroundColor: C.success, borderRadius: 3 },
  topbar: { minHeight: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: C.border, gap: 8 }, breadcrumb: { fontFamily: F.body, fontSize: 12, color: C.textSecondary }, previewLink: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 48 }, previewText: { fontFamily: F.bodyMedium, fontSize: 12, color: C.text }, smallBrand: { backgroundColor: C.primary, padding: 6, borderRadius: 10 },
  content: { paddingTop: 32, paddingBottom: 16, width: '100%', maxWidth: 1500, alignSelf: 'center', gap: 24 }, pageHeading: { flexDirection: 'row', alignItems: 'center', gap: 16 }, title: { fontFamily: F.headingBold, fontSize: 38, lineHeight: 49, color: C.text, letterSpacing: -1.4, marginTop: 8 }, subtitle: { ...TypeScale.body, color: C.textSecondary, marginTop: 4 },
  hero: { borderRadius: 24, padding: 32, minHeight: 262, flexDirection: 'row', overflow: 'hidden' }, heroPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#FFFDF9AA', alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 }, amberDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: C.accentText }, heroPillText: { fontFamily: F.bodyMedium, fontSize: 10, color: '#7F4C1B' }, heroTitle: { fontFamily: F.headingBold, fontSize: 34, lineHeight: 42, letterSpacing: -1.1, color: C.text, marginTop: 12 }, heroCopy: { ...TypeScale.body, color: '#745131', fontSize: 12, marginTop: 10 }, heroTag: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: '#FFFFFF70', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 }, heroTagText: { fontFamily: F.bodyMedium, fontSize: 10, color: '#654322' },
  heroArt: { width: '43%', alignItems: 'center', justifyContent: 'center' }, orbit: { position: 'absolute', width: 300, height: 300, borderWidth: 1, borderColor: '#FFFDF955', borderRadius: 150 }, orbitInner: { position: 'absolute', width: 226, height: 226, borderWidth: 1, borderColor: '#FFFDF977', borderRadius: 120 }, sunDisc: { width: 138, height: 138, borderRadius: 69, backgroundColor: '#FBC346', borderWidth: 8, borderColor: '#FFDE88', alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '12deg' }], ...WarmShadow }, floatingChat: { position: 'absolute', top: 7, left: 8, padding: 14, backgroundColor: '#FFFDF9', borderRadius: 18, flexDirection: 'row', alignItems: 'center', gap: 10, transform: [{ rotate: '-7deg' }], ...WarmShadow }, floatingPeople: { position: 'absolute', bottom: 3, right: -6, flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.surface, padding: 10, borderRadius: 18, transform: [{ rotate: '5deg' }], ...WarmShadow }, miniAvatar: { width: 30, height: 30, borderRadius: 15, borderWidth: 2, borderColor: C.surface, alignItems: 'center', justifyContent: 'center' }, sparkOne: { position: 'absolute', top: 23, right: -8 }, sparkTwo: { position: 'absolute', bottom: 23, left: 15 },
  toolbar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 16 }, tabs: { flexDirection: 'row', gap: 4, backgroundColor: '#F5EFE6', padding: 4, borderRadius: 12, alignSelf: 'flex-start' }, tab: { minHeight: 40, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 7, borderRadius: 9 }, tabActive: { backgroundColor: C.surface, ...WarmShadow }, tabText: { fontFamily: F.bodyMedium, fontSize: 12, color: C.textSecondary }, tabCount: { fontFamily: F.bodyMedium, fontSize: 9, color: C.textSecondary, backgroundColor: '#EAE2D8', paddingHorizontal: 5, paddingVertical: 2, borderRadius: 4 },
  panel: { backgroundColor: C.surface, borderRadius: 20, borderWidth: 1, borderColor: C.border, padding: 24, flex: 1 }, panelHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, sectionNumber: { fontFamily: F.bodyMedium, fontSize: 10, color: '#998572', backgroundColor: C.section, borderRadius: 6, padding: 6 }, panelTitle: { fontFamily: F.headingBold, fontSize: 18, color: C.text, letterSpacing: -0.4 }, panelSubtitle: { fontFamily: F.body, fontSize: 12, lineHeight: 19, color: C.textSecondary, marginTop: 8, marginBottom: 24 },
  swatches: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, rowGap: 24 }, swatch: { gap: 3 }, colorBlock: { height: 80, borderRadius: 12, borderWidth: 1, marginBottom: 8, padding: 9, justifyContent: 'flex-end' }, swatchIndex: { fontFamily: F.bodyMedium, fontSize: 9 }, colorName: { fontFamily: F.bodySemiBold, fontSize: 11, color: C.text }, hex: { fontFamily: F.bodyMedium, color: '#9C8B7A', fontSize: 10, marginTop: 5 }, statusRow: { flexDirection: 'row', gap: 12, alignItems: 'center', borderTopWidth: 1, borderColor: '#F5EBDD', paddingTop: 16, marginTop: 24 },
  typeGrid: { flexDirection: 'row', gap: 32 }, typeIntro: { flex: 0.8, justifyContent: 'center', backgroundColor: C.section, padding: 24, borderRadius: 16 }, typeLetters: { fontFamily: F.headingBold, fontSize: 90, lineHeight: 108, letterSpacing: -6, color: C.text }, fontNames: { fontFamily: F.headingBold, color: C.text, fontSize: 19, marginBottom: 12 }, typeRows: { flex: 1.4, gap: 12 }, typeRow: { flexDirection: 'row', gap: 16, paddingBottom: 12, borderBottomWidth: 1, borderColor: '#F6EFE6', alignItems: 'center' }, typeLabel: { width: 64, fontFamily: F.bodyMedium, fontSize: 10, color: C.textSecondary }, typeSpec: { fontFamily: F.body, fontSize: 9, color: '#9B8B7D', marginTop: 4 },
  shapeGrid: { flexDirection: 'row', gap: 32 }, spaceExamples: { flexDirection: 'row', alignItems: 'flex-end', gap: 24, marginVertical: 20 }, componentGrid: { flexDirection: 'row', gap: 24 }, column: { flex: 1, minWidth: 0 }, twoButtons: { flexDirection: 'row', gap: 8 }, divider: { height: 1, backgroundColor: C.border, marginVertical: 4 },
  cardGrid: { flexDirection: 'row', gap: 24 }, eventCard: { backgroundColor: C.surface, borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: C.border, ...WarmShadow }, eventImageWrap: { height: 192 }, eventImage: { width: '100%', height: '100%' }, imageBadges: { position: 'absolute', top: 12, right: 12, left: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eventBody: { padding: 20, gap: 10 }, eventTitle: { fontFamily: F.headingBold, fontSize: 20, lineHeight: 28, letterSpacing: -0.5, color: C.text }, eventFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderColor: C.border, marginTop: 8, paddingTop: 16, gap: 8 }, hostAvatar: { width: 36, height: 36, borderRadius: 18 },
  profileCard: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 20, padding: 20, gap: 20 }, profileHead: { flexDirection: 'row', alignItems: 'center', gap: 16 }, profilePhoto: { width: 64, height: 64, borderRadius: 24 }, profileStats: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: C.section, borderRadius: 16, padding: 16, gap: 8 }, statValue: { fontFamily: F.headingBold, fontSize: 20, color: C.text }, statDivider: { height: 32, width: 1, backgroundColor: C.border }, safetyCard: { backgroundColor: '#F0F6EB', borderRadius: 16, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 12 }, safetyIcon: { backgroundColor: '#E3EED9', width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  appBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: C.section, borderRadius: 16, padding: 12 }, navNote: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.section, padding: 16, gap: 12, borderRadius: 12 }, sheetPreview: { backgroundColor: C.section, borderWidth: 1, borderColor: C.border, borderRadius: 20, padding: 20, gap: 20 }, handle: { width: 36, height: 4, borderRadius: 3, backgroundColor: C.border, alignSelf: 'center' }, sheetSmiley: { width: 52, height: 52, borderRadius: 18, backgroundColor: C.primarySoft, alignItems: 'center', justifyContent: 'center' },
  iconGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, iconTile: { width: 68, minHeight: 76, backgroundColor: C.section, borderRadius: 12, alignItems: 'center', justifyContent: 'center', gap: 10 }, iconName: { fontFamily: F.body, fontSize: 8, color: C.textSecondary },
  chatGrid: { flexDirection: 'row', gap: 32 }, receivedBubble: { alignSelf: 'flex-start', backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 18, borderBottomLeftRadius: 4, padding: 16, maxWidth: '90%', gap: 5 }, sentBubble: { alignSelf: 'flex-end', backgroundColor: C.primarySoft, borderRadius: 18, borderBottomRightRadius: 4, padding: 16, maxWidth: '90%', gap: 5 }, chatAuthor: { fontFamily: F.bodySemiBold, fontSize: 9, letterSpacing: 0.8, color: C.accentText }, chatTime: { fontFamily: F.body, fontSize: 9, color: C.textSecondary, alignSelf: 'flex-end' },
  empty: { padding: 40, gap: 16, alignItems: 'center' }, footer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, gap: 16 }, footerText: { fontFamily: F.body, fontSize: 11, color: C.textSecondary, flexShrink: 1 }, tokenCode: { fontFamily: 'monospace', fontSize: 12, lineHeight: 19, color: C.text, backgroundColor: C.section, padding: 16, borderRadius: 12 },
});
